#version: '3.9'
#
#services:
#  postgres:
#    image: postgres:14-alpine
#    ports:
#      - 5433:5432
#    volumes:
#      - ~/apps/postgres:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=S3cret
#      - POSTGRES_USER=citizix_user
#      - POSTGRES_DB=citizix_db
volumes:
  pg_boran:

services:
  boran_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=citizix_user
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_DB=citizix_db
    volumes:
      - pg_boran:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432"

  diploma_app:
    restart: always
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - boran_db
    environment:
      POSTGRES_PASSWORD: 'S3cret'
      POSTGRES_USER: 'citizix_user'
      PGHOST: boran_db
      PGPORT: '5432'
      POSTGRES_DB: 'citizix_db'
      PORT: '8080'
      SPRING_PROFILE: 'docker'
#    links:
#      - diploma_db